### ISSUE TITLE
Uninstall possible?

### ISSUE THREAD

**Issue by brightcolor** [SergiX44/ISPCHelper#3]
Hello,

I want to uninstall the compiled versions - how can i do that?

**Comment by sergix44** [comment]
Right now the script can only install or update php versions.
To remove a compiled version you should delete the folder in `/opt`, and the init scripts, e.g.:
```
service php70-fpm stop
insserv -r php70-fpm
systemctl disable php70-fpm.service
rm /lib/systemd/system/php70-fpm.service
systemctl daemon-reload
systemctl reset-failed
```
