### ISSUE TITLE
APCu extension

### ISSUE THREAD

**Issue by dmgeurts** [SergiX44/ISPCHelper#35]
Any suggestions to compiling APCu, as the /usr/local/src/php-build is emptied after the script is run?

Or maybe this could be included as an option when compiling?

**Comment by sergix44** [comment]
You can simply install it via pecl, https://pecl.php.net/package/APCU

just go in `/opt/phpXX/bin/` and run `./pecl install apcu`

**Comment by dmgeurts** [comment]
I guess I'm missing something?

```
/opt/php74/bin$ ./pecl install apcu
bash: ./pecl: No such file or directory
```

**Comment by dmgeurts** [comment]
Related?

```
Configuring PEAR
checking whether to install PEAR... no
```

**Comment by sergix44** [comment]
Update the script from the repository, pear support was added not so long ago, and than yes, you should recompile the target version, and you'll get pecl&pear

**Comment by dmgeurts** [comment]
I had an old version in the folder I was in. wget downloaded the file with a new name. I used the single-line command from read.me.

Thank you!
