### ISSUE TITLE
How to add modules after install

### ISSUE THREAD

**Issue by schwim0341** [SergiX44/ISPCHelper#5]
Hi there and thanks for the script, the install went fantastic! I do have a question relating to the PHP install.  I can't seem to figure out how to add modules afterward. Could you perhaps let me know how I might go about performing that?  This is on a Debian 9 machine.  The module I've been trying to enable for the last couple of days is intl.

Thanks for your time!

**Comment by Pe46dro** [comment]
We are going to add Intl in #7 

From [PHP Manual](http://php.net/manual/en/intl.installation.php):
> This extension may be installed using the bundled version as of PHP 5.3.0, or as a PECL extension as of PHP 5.2.0. In other words, there are two methods to install the intl extension.

The PECL package is not maintained anymore and has been superseded.
So you have to add --enable-intl while compiling PHP.
