### ISSUE TITLE
openssl Not Found

### ISSUE THREAD

**Issue by Lukasss93** [SergiX44/ISPCHelper#74]
OS: Ubuntu 22.04 (WSL)

Compiling...
--2023-11-24 21:08:10--  http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 185.125.190.36, 91.189.91.82, 185.125.190.39, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|185.125.190.36|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-11-24 21:08:10 ERROR 404: Not Found.

Error detected in latest command, exiting...

**Comment by Pe46dro** [comment]
[On readme currently-supported-platforms](https://github.com/sergix44/ISPC-PHPCompiler/blob/bash-version/README.md#currently-supported-platforms)
`(*) on Ubuntu 22.x PHP <= 8.0 only without OpenSSL`
